### ISSUE TITLE
CRITICAL: Inkorrekt implementation av move

### ISSUE THREAD

**Issue by WilliamFrisk** [Lee4-M/TDA553-lab1-grupp36#3]
Koden nedan fungerar nog inte riktigt som ni tänkt. Kom ihåg att positiva y-axeln pekar nedåt i programmering. Det innebär att turnLeft() och turnRight() har motsatt effekt.

https://github.com/Lee4-M/TDA553-lab1-grupp36/blob/8c00e8956743e6539c032eb14190cdcc94c3f663/src/car/Car.java#L133-L141

**Comment by WilliamFrisk** [comment]
Vidare kan tilläggas att konventionen är att direkt tilldela attribut värden istället för att gå igenom setters och getters om det är inom klassen. Det gör koden mer läsbar :)

**Comment by Lee4-M** [comment]
Ändrade nu så att det står - på turnleft och + på turnright! Ska också vara så att directionAngle tilldelas värdet direkt istället

**Comment by WilliamFrisk** [comment]
Snyggt jobbat!
